-- MySQL Script generated by MySQL Workbench
-- mié 22 mar 2017 23:35:21 CLST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Elem3ntalDevelopment
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Elem3ntalDevelopment` ;

-- -----------------------------------------------------
-- Schema Elem3ntalDevelopment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Elem3ntalDevelopment` DEFAULT CHARACTER SET utf8 ;
USE `Elem3ntalDevelopment` ;

-- -----------------------------------------------------
-- Table `Elem3ntalDevelopment`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Elem3ntalDevelopment`.`messages` ;

CREATE TABLE IF NOT EXISTS `Elem3ntalDevelopment`.`messages` (
  `Mess_id` INT NOT NULL AUTO_INCREMENT,
  `Mess_email` VARCHAR(45) NOT NULL,
  `Mess_text` TEXT NOT NULL,
  `Mess_date` DATETIME NOT NULL,
  PRIMARY KEY (`Mess_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Elem3ntalDevelopment`.`visitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Elem3ntalDevelopment`.`visitas` ;

CREATE TABLE IF NOT EXISTS `Elem3ntalDevelopment`.`visitas` (
  `visitas_id` INT NOT NULL AUTO_INCREMENT,
  `visitas_IP` VARCHAR(70) NOT NULL,
  `visitas_date` DATETIME NOT NULL,
  PRIMARY KEY (`visitas_id`))
ENGINE = InnoDB;

USE `Elem3ntalDevelopment` ;

-- -----------------------------------------------------
-- function dejarMensaje
-- -----------------------------------------------------

USE `Elem3ntalDevelopment`;
DROP function IF EXISTS `Elem3ntalDevelopment`.`dejarMensaje`;

DELIMITER $$
USE `Elem3ntalDevelopment`$$
CREATE FUNCTION  dejarMensaje(_email VARCHAR(45), _mensaje TEXT) RETURNS INTEGER
BEGIN
	INSERT INTO Elem3ntalDevelopment.messages(Mess_email,Mess_text,Mess_date) VALUES(_email,_mensaje,NOW());
	return 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function registrarVisita
-- -----------------------------------------------------

USE `Elem3ntalDevelopment`;
DROP function IF EXISTS `Elem3ntalDevelopment`.`registrarVisita`;

DELIMITER $$
USE `Elem3ntalDevelopment`$$
CREATE FUNCTION registrarVisita(_IP VARCHAR(70)) RETURNS INTEGER
BEGIN
	INSERT INTO Elem3ntalDevelopment.visitas(visitas_IP,visitas_date) VALUES(_IP,now());
	RETURN 1;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
